apiVersion: v1
kind: Service
metadata:
  name: pangolin
  namespace: pangolin
  labels:
    app: pangolin
spec:
  type: ClusterIP
  ports:
    - port: 4181
      targetPort: 4181
      protocol: TCP
      name: http
  selector:
    app: pangolin
