apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: traefik
type: Opaque
stringData:
  email: "YOUR_EMAIL@example.com"  # Replace with your Cloudflare email
  apiToken: "YOUR_CLOUDFLARE_API_TOKEN"  # Replace with your Cloudflare API token
